### ISSUE TITLE
Report code should be word-wrapped

### ISSUE THREAD

**Issue by m-alger** [chromium/caterpillar#39]
Currently, code shown in the report overflows the container. This should be word-wrapped so it looks nicer and is easier to read.

This should be a matter of adding some CSS to report.css, e.g.

``` css
.prettyprint {
    word-wrap: break-word;
}
```
